services:
  couchdb:
    image: apache/couchdb:3.5
    container_name: couchdb
    restart: unless-stopped
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    ports:
      - "${COUCHDB_PORT}:5984"
    volumes:
      - "${COUCHDB_DATA}:/opt/couchdb/data"
    networks:
      - common-proxy_default

networks:
  common-proxy_default:
    external: true