#!/usr/bin/python
from __future__ import print_function
from collections import OrderedDict
import os
getlogin = lambda: pwd.getpwuid(os.getuid())[0]
user=getlogin()
path="/home/"+user+"/"
file=".bash_history"
fin=open(path+file, "r")
uniq=OrderedDict()
for l in fin:
	line=l.strip()
	if line in uniq:	del(uniq[line])
	uniq[line]=True
fout=open(path+file, "w")
for line in uniq:	print(line, file=fout)
fout.close()
print("History cleaned!")
