#!/bin/bash

max_length=128
length="${1:-20}"
charset="${2:-alnum}"

if [ "$length" -gt "$max_length" ]; then
    echo "Error: Maximum password length is $max_length characters" >&2
    exit 1
fi

case "$charset" in
num) chars='0-9' ;;
alpha) chars='a-zA-Z' ;;
alnum) chars='a-zA-Z0-9' ;;
all) chars='a-zA-Z0-9!@#$%^&*()_+-=[]{}|;:,.<>?~' ;;
*)
    echo "Invalid charset: $charset. Use: num, alpha, alnum, all" >&2
    exit 1
    ;;
esac

head -c "$((length * 10))" /dev/urandom | LC_ALL=C tr -dc "$chars" | head -c "$length"
echo
