services:

  gogs:
    image: gogs/gogs
    restart: always
    ports:
      - "10880:3000"
      - "10022:22"
    volumes:
      - .:/data
    depends_on:
      - db
    networks:
      - proxy-network
      - gogs-network

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - gogs-network

networks:
  proxy-network:
    external: true
  gogs-network:
    external: false